"""empty message

Revision ID: 4b59d0c01d56
Revises: 92492d07fafa
Create Date: 2018-07-16 17:16:03.594787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b59d0c01d56'
down_revision = '92492d07fafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('headimg', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'headimg')
    # ### end Alembic commands ###
