"""empty message

Revision ID: 5bbb5bd2fe56
Revises: 93fbaf652f64
Create Date: 2018-07-16 21:18:05.147061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbb5bd2fe56'
down_revision = '93fbaf652f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('subtitle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'subtitle')
    # ### end Alembic commands ###
