"""empty message

Revision ID: facd682e7e1c
Revises: f11e054eaf60
Create Date: 2019-02-11 20:27:00.718120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facd682e7e1c'
down_revision = 'f11e054eaf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'description')
    # ### end Alembic commands ###
